// import or require all necessary packages
const express = require('express')
const webpush = require('web-push');
const cors = require('cors');
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const Subscription = require('./models/subscription');

// set keys to create use webPush API (generated by console Tool)
const vapidKeys = {
  "publicKey": "BK50oaFrXUMC5p9jknpbzY7tCWuwGkAu6eQYe-UNDuTgmdEHQYiJCVHBuQY21_KpO80ctgvW3Fq_qgB_gl_EDR0",
  "privateKey": "xWYxPp06EZ0bcFfGKBrDSTX4kEvH5N8TDErCR44Fkdw"
};

// create server and aquire middleware
const app = express();
app.use(cors());
app.use(bodyParser.json());

// configure webPush
webpush.setVapidDetails(
  'mailto:test@test.de',
  vapidKeys.publicKey,
  vapidKeys.privateKey
);

// set port to listen for requests
const PORT = process.env.PORT || 8080;

// Connect to database
const databaseUri = 'mongodb+srv://admin:nimda@ep-projekt-database.9tmj5.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
mongoose.connect(databaseUri)
  .then(() => {
    // start server
    app.listen(PORT, () => {
      console.log('Server is running on Port', PORT)
    })
  })
  .catch(err => console.log(err));

// endpoint to create an subscription object in the database that can later be used to send webPush messages to the client
app.post('/notifications', (req, res) => {
  // create subsciption
  new Subscription(req.body.sub).save()
    // if subscription created
    .then(() => {
      res.status(200).json({message: "Subscription added successfully."});
    })
    // if error while creating subscription
    .catch(() => {
      console.log('Error creating subscription');
      res.status(500).json({message: 'Error creating subscription'})
    })
})

// endpoint to send an webPush message to all subscribed clients
app.post('/newsletter', (req, res) => {

  // set message to payload from api call
  const notificationPayload = req.body.notification;

  // get all subscription objects from database
  Subscription.find({}).exec().then(data => {
    // use webPush package to send message to client
    Promise.all(data.map(sub => webpush.sendNotification(sub, JSON.stringify(notificationPayload))))
      .then(() => res.status(200).json({message: 'Newsletter sent successfully.'}))
      .catch(err => {
        console.error("Error sending notification, reason: ", err);
        res.sendStatus(500);
      });
  })
})
